- name: Generate an RSA key pair
  command: ssh-keygen -t rsa -b 2048 -f /home/vagrant/.ssh/id_rsa -q -N ""
  args:
    creates: /home/vagrant/.ssh/id_rsa
  become: true
  become_user: vagrant

- name: Copy the public key to /vagrant
  copy:
    src: /home/vagrant/.ssh/id_rsa.pub
    dest: /vagrant/id_rsa.pub
    owner: "vagrant"
    group: "vagrant"
    mode: '0644'
    remote_src: yes