- name: Copy a new network configuration "interfaces" file into place, after passing validation with ifup
  become: true
  ansible.builtin.copy:
    src: eth1_static
    dest: /etc/network/interfaces.d/eth1
    validate: /usr/sbin/ifup --no-act -i %s eth1
  notify: Restart Networking

- name: Change allow-hotplug with auto
  become: true
  ansible.builtin.replace:
    path: "/etc/network/interfaces"
    regexp: "allow-hotplug"
    replace: "auto"
    validate: /usr/sbin/ifup --no-act -i %s eth0
