- name: Add apt channels
  ansible.builtin.replace:
    path: "/etc/apt/sources.list"
    regexp: "main"
    replace: "main contrib non-free"

- name: Install SNMP
  ansible.builtin.apt:
    update_cache: true
    pkg:
      - snmp
      - snmp-mibs-downloader

- name: Comment line in /etc/snmp/snmp.conf
  replace:
    path: /etc/snmp/snmp.conf
    regexp: "^mibs"
    replace: "# mibs"